name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Push to Mirror Repository
        run: |
          git remote add mirror https://aliz1369:${{ secrets.GIT_CREDENTIALS }}@github.com/aliz1369/finnovation-website.git
          git push --mirror mirror
